name: renovate
on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 1-5"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_BOT_TOKEN }}
      - name: Renovate
        uses: renovatebot/github-action@v46
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ secrets.GH_BOT_TOKEN }}
        env:
          RENOVATE_AUTOMERGE: true
